apiVersion: v1
kind: Service
metadata:
  name: pwck8s-backend
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    pwck8s.io/app: pwck8s-backend
    pwck8s.io/component: backend